name = "kizai-sys-api"
version = "1.0.0"
description = "My Spring Boot application"

[phases.setup]
cmds = [
  "mvn dependency:purge-local-repository",
  "mvn clean install"
]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar ${APP_JAR}"
