name = "kizai-sys-api"
version = "1.0.0"
description = "My Spring Boot application"

[phases.setup]
cmds = ["./gradlew clean"]

[phases.build]
cmds = ["./gradlew build -x test"]

[start]
cmd = "java -jar ${APP_JAR}"

